version: '2'

networks:
  my-network:
    driver: bridge

services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/mypostgres/postgresql'
    environment:
      POSTGRES_USER: joni
      POSTGRES_PASSWORD: password312
      POSTGRES_DB: my_database
    networks:
      - my-network

volumes:
  postgresql_data:
    driver: local
